name: warehouse-system

include:
    - Common/docker-compose.infra.yml
        
services:
    warehouse.inventory.api:
        image: warehouse.inventory.api
        ports:
            - "5001:8080"
        networks:
            - warehouse-net
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=inventorydb;Username=admin;Password=AdminTest!234%
            - RabbitMq__HostName=rabbitmq
            - RabbitMq__UserName=${RABBITMQ_USER}
            - RabbitMq__Password=${RABBITMQ_PASSWORD}
            - Services__ProductApi__BaseUrl=http://warehouse.product.api:8080
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
            - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
            - Authentication__Keycloak__Authority=http://keycloak:8080/realms/Warehouse.Identity
            - Authentication__Keycloak__MetadataAddress=http://keycloak:8080/realms/Warehouse.Identity/.well-known/openid-configuration
            - Authentication__Keycloak__RequireHttpsMetadata=false
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 10s
        depends_on:
            postgres:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        build:
            context: .
            dockerfile: Inventory/src/Warehouse.Inventory.Api/Dockerfile

    warehouse.product.api:
        image: warehouse.product.api
        ports:
            - "5002:8080"
        networks:
            - warehouse-net
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=productdb;Username=admin;Password=AdminTest!234%
            - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
            - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
            - RabbitMq__HostName=rabbitmq
            - RabbitMq__UserName=warehouse_admin
            - RabbitMq__Password=warehouse_password123
            - Authentication__Keycloak__Authority=http://keycloak:8080/realms/Warehouse.Identity
            - Authentication__Keycloak__MetadataAddress=http://keycloak:8080/realms/Warehouse.Identity/.well-known/openid-configuration
            - Authentication__Keycloak__RequireHttpsMetadata=false
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
            interval: 10s
            timeout: 5s
            retries: 3
            start_period: 10s
        depends_on:
            postgres:
                condition: service_healthy
            rabbitmq:
                condition: service_healthy
        build:
            context: .
            dockerfile: Product/src/Warehouse.Product.Api/Dockerfile
