@apiUrl = https://localhost:7031
@keycloakUrl = http://localhost:8080
@realm = Warehouse.Identity
@clientId = test-client

@usernameRead = bob.reader
@usernameWrite = johny.writer
@password = test1234


### Get token from Keycloaka (read)
POST {{keycloakUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&username={{usernameRead}}&password={{password}}&grant_type=password&scope=openid profile email roles
> {%
    client.test("Login successfully", function() {
        client.assert(response.status === 200, "Problem with logging");
    });
    client.global.set("auth_token", response.body.access_token);
%}


### Get token from Keycloaka (read + write)
POST {{keycloakUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&username={{usernameWrite}}&password={{password}}&grant_type=password&scope=openid profile email roles
> {%
    client.test("Login successfully", function() {
        client.assert(response.status === 200, "Problem with logging");
    });
    client.global.set("auth_token", response.body.access_token);
%}

### Adding inventory (Required role 'write')
# @name CreateInventory
POST {{apiUrl}}/api/v1.0/inventories
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
    "productId": "2b2e246d-2d89-4f1c-a73c-a712876006ae",
    "quantity": 15
}

### Ger inventories
GET {{apiUrl}}/api/v1.0/inventories
Authorization: Bearer {{auth_token}}