// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.MasterData.Partners.Infrastructure.Persistence;

#nullable disable

namespace Warehouse.MasterData.Partners.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PartnersDbContext))]
    [Migration("20260614172503_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("partners")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.MasterData.Partners.Domain.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("tax_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("parties", "partners");
                });

            modelBuilder.Entity("Warehouse.MasterData.Partners.Domain.PartyRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<Guid?>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<string>("role_type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.HasKey("Id");

                    b.HasIndex("PartyId");

                    b.ToTable("party_roles", "partners");

                    b.HasDiscriminator<string>("role_type").HasValue("PartyRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Warehouse.MasterData.Partners.Domain.CarrierRole", b =>
                {
                    b.HasBaseType("Warehouse.MasterData.Partners.Domain.PartyRole");

                    b.PrimitiveCollection<int[]>("Services")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasDiscriminator().HasValue("carrier");
                });

            modelBuilder.Entity("Warehouse.MasterData.Partners.Domain.CustomerRole", b =>
                {
                    b.HasBaseType("Warehouse.MasterData.Partners.Domain.PartyRole");

                    b.HasDiscriminator().HasValue("customer");
                });

            modelBuilder.Entity("Warehouse.MasterData.Partners.Domain.SupplierRole", b =>
                {
                    b.HasBaseType("Warehouse.MasterData.Partners.Domain.PartyRole");

                    b.HasDiscriminator().HasValue("supplier");
                });

            modelBuilder.Entity("Warehouse.MasterData.Partners.Domain.Party", b =>
                {
                    b.OwnsOne("Warehouse.MasterData.Partners.Domain.ContactInfo", "Contact", b1 =>
                        {
                            b1.Property<Guid>("PartyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Email")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("contact_email");

                            b1.Property<string>("Phone")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("contact_phone");

                            b1.HasKey("PartyId");

                            b1.ToTable("parties", "partners");

                            b1.WithOwner()
                                .HasForeignKey("PartyId");
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.MasterData.Partners.Domain.PartyRole", b =>
                {
                    b.HasOne("Warehouse.MasterData.Partners.Domain.Party", null)
                        .WithMany("Roles")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Warehouse.MasterData.Partners.Domain.CustomerRole", b =>
                {
                    b.OwnsMany("Warehouse.SharedKernel.ValueObjects.Address", "ShippingAddresses", b1 =>
                        {
                            b1.Property<Guid>("CustomerRoleId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street");

                            b1.HasKey("CustomerRoleId", "Id");

                            b1.ToTable("customer_shipping_addresses", "partners");

                            b1.WithOwner()
                                .HasForeignKey("CustomerRoleId");
                        });

                    b.Navigation("ShippingAddresses");
                });

            modelBuilder.Entity("Warehouse.MasterData.Partners.Domain.Party", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
