// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.Logistics.Core.Infrastructure.Persistence;

#nullable disable

namespace Warehouse.Logistics.Core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LogisticsDbContext))]
    [Migration("20260624210910_AddOrderResolutionAndPackageDims")]
    partial class AddOrderResolutionAndPackageDims
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("logistics")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Logistics.Core.Domain.InboundDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("Supplier")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_role_id");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("warehouse_code");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("inbound_deliveries", "logistics");
                });

            modelBuilder.Entity("Warehouse.Logistics.Core.Domain.OutboundOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Customer")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_role_id");

                    b.Property<DateTimeOffset>("RequiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("required_at");

                    b.Property<string>("Resolution")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("resolution");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("warehouse_code");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("outbound_orders", "logistics");
                });

            modelBuilder.Entity("Warehouse.Logistics.Core.Domain.PickList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("pick_lists", "logistics");
                });

            modelBuilder.Entity("Warehouse.Logistics.Core.Domain.Replicas.CatalogProductSnapshot", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_code");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("base_unit");

                    b.Property<bool>("IsBatchTracked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_batch_tracked");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Code");

                    b.ToTable("catalog_product_snapshots", "logistics");
                });

            modelBuilder.Entity("Warehouse.Logistics.Core.Domain.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Carrier")
                        .HasColumnType("uuid")
                        .HasColumnName("carrier_role_id");

                    b.Property<DateTimeOffset?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Tracking")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tracking_number");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("shipments", "logistics");
                });

            modelBuilder.Entity("Warehouse.Logistics.Core.Domain.InboundDelivery", b =>
                {
                    b.OwnsOne("Warehouse.Logistics.Core.Domain.DockSlot", "Slot", b1 =>
                        {
                            b1.Property<Guid>("InboundDeliveryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DockCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("slot_dock_code");

                            b1.Property<DateTimeOffset>("From")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("slot_from");

                            b1.Property<DateTimeOffset>("To")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("slot_to");

                            b1.HasKey("InboundDeliveryId");

                            b1.ToTable("inbound_deliveries", "logistics");

                            b1.WithOwner()
                                .HasForeignKey("InboundDeliveryId");
                        });

                    b.OwnsMany("Warehouse.Logistics.Core.Domain.DeliveryLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("delivery_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("LineNo")
                                .HasColumnType("integer")
                                .HasColumnName("line_no");

                            b1.Property<string>("Discrepancy")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("discrepancy");

                            b1.Property<string>("Note")
                                .HasMaxLength(512)
                                .HasColumnType("character varying(512)")
                                .HasColumnName("note");

                            b1.Property<string>("Product")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("product_code");

                            b1.HasKey("delivery_id", "LineNo");

                            b1.ToTable("inbound_delivery_lines", "logistics");

                            b1.WithOwner()
                                .HasForeignKey("delivery_id");

                            b1.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Actual", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryLinedelivery_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("DeliveryLineLineNo")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("numeric(18,3)")
                                        .HasColumnName("actual_amount");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("actual_unit");

                                    b2.HasKey("DeliveryLinedelivery_id", "DeliveryLineLineNo");

                                    b2.ToTable("inbound_delivery_lines", "logistics");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryLinedelivery_id", "DeliveryLineLineNo");
                                });

                            b1.OwnsOne("Warehouse.Logistics.Core.Domain.BatchInfo", "Batch", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryLinedelivery_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("DeliveryLineLineNo")
                                        .HasColumnType("integer");

                                    b2.Property<DateOnly?>("ExpiryDate")
                                        .HasColumnType("date")
                                        .HasColumnName("batch_expiry");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)")
                                        .HasColumnName("batch_number");

                                    b2.HasKey("DeliveryLinedelivery_id", "DeliveryLineLineNo");

                                    b2.ToTable("inbound_delivery_lines", "logistics");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryLinedelivery_id", "DeliveryLineLineNo");
                                });

                            b1.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Expected", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryLinedelivery_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("DeliveryLineLineNo")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("numeric(18,3)")
                                        .HasColumnName("expected_amount");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("expected_unit");

                                    b2.HasKey("DeliveryLinedelivery_id", "DeliveryLineLineNo");

                                    b2.ToTable("inbound_delivery_lines", "logistics");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryLinedelivery_id", "DeliveryLineLineNo");
                                });

                            b1.OwnsOne("Warehouse.Logistics.Core.Domain.DeliveryPack", "Pack", b2 =>
                                {
                                    b2.Property<Guid>("DeliveryLinedelivery_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("DeliveryLineLineNo")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("FactorToBase")
                                        .HasPrecision(18, 4)
                                        .HasColumnType("numeric(18,4)")
                                        .HasColumnName("pack_factor");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("pack_unit");

                                    b2.HasKey("DeliveryLinedelivery_id", "DeliveryLineLineNo");

                                    b2.ToTable("inbound_delivery_lines", "logistics");

                                    b2.WithOwner()
                                        .HasForeignKey("DeliveryLinedelivery_id", "DeliveryLineLineNo");
                                });

                            b1.Navigation("Actual");

                            b1.Navigation("Batch");

                            b1.Navigation("Expected")
                                .IsRequired();

                            b1.Navigation("Pack");
                        });

                    b.Navigation("Lines");

                    b.Navigation("Slot");
                });

            modelBuilder.Entity("Warehouse.Logistics.Core.Domain.OutboundOrder", b =>
                {
                    b.OwnsOne("Warehouse.SharedKernel.ValueObjects.Address", "ShipTo", b1 =>
                        {
                            b1.Property<Guid>("OutboundOrderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("ship_to_city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("ship_to_country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("ship_to_postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("ship_to_street");

                            b1.HasKey("OutboundOrderId");

                            b1.ToTable("outbound_orders", "logistics");

                            b1.WithOwner()
                                .HasForeignKey("OutboundOrderId");
                        });

                    b.OwnsMany("Warehouse.Logistics.Core.Domain.OrderLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("order_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("LineNo")
                                .HasColumnType("integer")
                                .HasColumnName("line_no");

                            b1.Property<string>("Product")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("product_code");

                            b1.HasKey("order_id", "LineNo");

                            b1.ToTable("outbound_order_lines", "logistics");

                            b1.WithOwner()
                                .HasForeignKey("order_id");

                            b1.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Ordered", b2 =>
                                {
                                    b2.Property<Guid>("OrderLineorder_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("OrderLineLineNo")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("numeric(18,3)")
                                        .HasColumnName("ordered_amount");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("ordered_unit");

                                    b2.HasKey("OrderLineorder_id", "OrderLineLineNo");

                                    b2.ToTable("outbound_order_lines", "logistics");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderLineorder_id", "OrderLineLineNo");
                                });

                            b1.Navigation("Ordered")
                                .IsRequired();
                        });

                    b.Navigation("Lines");

                    b.Navigation("ShipTo")
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Logistics.Core.Domain.PickList", b =>
                {
                    b.OwnsMany("Warehouse.Logistics.Core.Domain.PickTask", "Tasks", b1 =>
                        {
                            b1.Property<Guid>("pick_list_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer")
                                .HasColumnName("sequence");

                            b1.Property<string>("HandledBy")
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("handled_by");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("location_code");

                            b1.Property<string>("Product")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("product_code");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("pick_list_id", "Sequence");

                            b1.ToTable("pick_tasks", "logistics");

                            b1.WithOwner()
                                .HasForeignKey("pick_list_id");

                            b1.OwnsOne("Warehouse.Logistics.Core.Domain.BatchInfo", "Batch", b2 =>
                                {
                                    b2.Property<Guid>("PickTaskpick_list_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("PickTaskSequence")
                                        .HasColumnType("integer");

                                    b2.Property<DateOnly?>("ExpiryDate")
                                        .HasColumnType("date")
                                        .HasColumnName("batch_expiry");

                                    b2.Property<string>("Number")
                                        .IsRequired()
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)")
                                        .HasColumnName("batch_number");

                                    b2.HasKey("PickTaskpick_list_id", "PickTaskSequence");

                                    b2.ToTable("pick_tasks", "logistics");

                                    b2.WithOwner()
                                        .HasForeignKey("PickTaskpick_list_id", "PickTaskSequence");
                                });

                            b1.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("PickTaskpick_list_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("PickTaskSequence")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("numeric(18,3)")
                                        .HasColumnName("qty_amount");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("qty_unit");

                                    b2.HasKey("PickTaskpick_list_id", "PickTaskSequence");

                                    b2.ToTable("pick_tasks", "logistics");

                                    b2.WithOwner()
                                        .HasForeignKey("PickTaskpick_list_id", "PickTaskSequence");
                                });

                            b1.Navigation("Batch");

                            b1.Navigation("Quantity")
                                .IsRequired();
                        });

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Warehouse.Logistics.Core.Domain.Shipment", b =>
                {
                    b.OwnsMany("Warehouse.Logistics.Core.Domain.Package", "Packages", b1 =>
                        {
                            b1.Property<Guid>("shipment_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Number")
                                .HasColumnType("integer")
                                .HasColumnName("number");

                            b1.Property<string>("Description")
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("description");

                            b1.Property<decimal>("Weight")
                                .HasPrecision(12, 3)
                                .HasColumnType("numeric(12,3)")
                                .HasColumnName("weight_kg");

                            b1.HasKey("shipment_id", "Number");

                            b1.ToTable("packages", "logistics");

                            b1.WithOwner()
                                .HasForeignKey("shipment_id");

                            b1.OwnsOne("Warehouse.Logistics.Core.Domain.PackageDimensions", "Dimensions", b2 =>
                                {
                                    b2.Property<Guid>("Packageshipment_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("PackageNumber")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("HeightCm")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("height_cm");

                                    b2.Property<decimal>("LengthCm")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("length_cm");

                                    b2.Property<decimal>("WidthCm")
                                        .HasPrecision(10, 2)
                                        .HasColumnType("numeric(10,2)")
                                        .HasColumnName("width_cm");

                                    b2.HasKey("Packageshipment_id", "PackageNumber");

                                    b2.ToTable("packages", "logistics");

                                    b2.WithOwner()
                                        .HasForeignKey("Packageshipment_id", "PackageNumber");
                                });

                            b1.Navigation("Dimensions")
                                .IsRequired();
                        });

                    b.Navigation("Packages");
                });
#pragma warning restore 612, 618
        }
    }
}
