// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.Warehousing.Inventory.Infrastructure.Persistence;

#nullable disable

namespace Warehouse.Warehousing.Inventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260624205049_AddStocktake")]
    partial class AddStocktake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventory")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("number");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("quality");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sku");

                    b.Property<string>("SupplierRef")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("supplier_ref");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Sku", "Number")
                        .IsUnique();

                    b.ToTable("batches", "inventory");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.HandlingUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("location");

                    b.Property<string>("Lpn")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lpn");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Lpn")
                        .IsUnique();

                    b.ToTable("handling_units", "inventory");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.Replicas.LocationSnapshot", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("code");

                    b.Property<decimal>("Capacity")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("capacity_m3");

                    b.Property<bool>("IsHazmatZone")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hazmat_zone");

                    b.Property<decimal>("MaxLoad")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("max_load_kg");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("room");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("warehouse");

                    b.HasKey("Code");

                    b.HasIndex("Warehouse", "Room");

                    b.ToTable("location_snapshots", "inventory");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.Replicas.ProductSnapshot", b =>
                {
                    b.Property<string>("Sku")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sku");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("base_unit");

                    b.Property<bool>("HasExpiryDate")
                        .HasColumnType("boolean")
                        .HasColumnName("has_expiry_date");

                    b.Property<bool>("IsBatchTracked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_batch_tracked");

                    b.Property<bool>("IsHazardous")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hazardous");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresColdChain")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_cold_chain");

                    b.Property<decimal>("UnitVolume")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)")
                        .HasColumnName("unit_volume_m3");

                    b.Property<decimal>("UnitWeight")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("unit_weight_kg");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Sku");

                    b.ToTable("product_snapshots", "inventory");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.StockItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Batch")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("batch");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("location");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Sku", "Batch", "Location")
                        .IsUnique();

                    b.ToTable("stock_items", "inventory");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Batch")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("batch");

                    b.Property<string>("From")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("from_location");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("performed_by");

                    b.Property<string>("Reason")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("reason");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sku");

                    b.Property<string>("To")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("to_location");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Sku", "OccurredAt");

                    b.ToTable("stock_movements", "inventory");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.StockReservation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("OrderRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("order_ref");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sku");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("warehouse");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OrderRef");

                    b.ToTable("stock_reservations", "inventory");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.Stocktake", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<string>("OrderedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("ordered_by");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("scope");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("stocktakes", "inventory");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.HandlingUnit", b =>
                {
                    b.OwnsMany("Warehouse.Warehousing.Inventory.Domain.HandlingUnitLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("handling_unit_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Batch")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("batch");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("sku");

                            b1.HasKey("handling_unit_id", "Id");

                            b1.ToTable("handling_unit_lines", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("handling_unit_id");

                            b1.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("HandlingUnitLinehandling_unit_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("HandlingUnitLineId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("numeric(18,3)")
                                        .HasColumnName("qty_amount");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("qty_unit");

                                    b2.HasKey("HandlingUnitLinehandling_unit_id", "HandlingUnitLineId");

                                    b2.ToTable("handling_unit_lines", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("HandlingUnitLinehandling_unit_id", "HandlingUnitLineId");
                                });

                            b1.Navigation("Quantity")
                                .IsRequired();
                        });

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.Replicas.LocationSnapshot", b =>
                {
                    b.OwnsOne("Warehouse.SharedKernel.ValueObjects.TemperatureRange", "EnvironmentTemperature", b1 =>
                        {
                            b1.Property<string>("LocationSnapshotCode")
                                .HasColumnType("character varying(60)");

                            b1.Property<decimal>("MaxCelsius")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("temp_max_c");

                            b1.Property<decimal>("MinCelsius")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("temp_min_c");

                            b1.HasKey("LocationSnapshotCode");

                            b1.ToTable("location_snapshots", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("LocationSnapshotCode");
                        });

                    b.Navigation("EnvironmentTemperature")
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.Replicas.ProductSnapshot", b =>
                {
                    b.OwnsOne("Warehouse.SharedKernel.ValueObjects.TemperatureRange", "RequiredTemperature", b1 =>
                        {
                            b1.Property<string>("ProductSnapshotSku")
                                .HasColumnType("character varying(32)");

                            b1.Property<decimal>("MaxCelsius")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("temp_max_c");

                            b1.Property<decimal>("MinCelsius")
                                .HasPrecision(6, 2)
                                .HasColumnType("numeric(6,2)")
                                .HasColumnName("temp_min_c");

                            b1.HasKey("ProductSnapshotSku");

                            b1.ToTable("product_snapshots", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("ProductSnapshotSku");
                        });

                    b.Navigation("RequiredTemperature");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.StockItem", b =>
                {
                    b.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Allocated", b1 =>
                        {
                            b1.Property<Guid>("StockItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("allocated_amount");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("allocated_unit");

                            b1.HasKey("StockItemId");

                            b1.ToTable("stock_items", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockItemId");
                        });

                    b.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "OnHand", b1 =>
                        {
                            b1.Property<Guid>("StockItemId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("on_hand_amount");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("on_hand_unit");

                            b1.HasKey("StockItemId");

                            b1.ToTable("stock_items", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockItemId");
                        });

                    b.OwnsMany("Warehouse.Warehousing.Inventory.Domain.Allocation", "Allocations", b1 =>
                        {
                            b1.Property<Guid>("stock_item_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("OrderRef")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("order_ref");

                            b1.Property<Guid>("ReservationId")
                                .HasColumnType("uuid")
                                .HasColumnName("reservation_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("status");

                            b1.HasKey("stock_item_id", "Id");

                            b1.ToTable("allocations", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("stock_item_id");

                            b1.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Quantity", b2 =>
                                {
                                    b2.Property<Guid>("Allocationstock_item_id")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("AllocationId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("numeric(18,3)")
                                        .HasColumnName("qty_amount");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("qty_unit");

                                    b2.HasKey("Allocationstock_item_id", "AllocationId");

                                    b2.ToTable("allocations", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("Allocationstock_item_id", "AllocationId");
                                });

                            b1.Navigation("Quantity")
                                .IsRequired();
                        });

                    b.Navigation("Allocated")
                        .IsRequired();

                    b.Navigation("Allocations");

                    b.Navigation("OnHand")
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.StockMovement", b =>
                {
                    b.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("StockMovementId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("qty_amount");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("qty_unit");

                            b1.HasKey("StockMovementId");

                            b1.ToTable("stock_movements", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockMovementId");
                        });

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.StockReservation", b =>
                {
                    b.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Allocated", b1 =>
                        {
                            b1.Property<Guid>("StockReservationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("allocated_amount");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("allocated_unit");

                            b1.HasKey("StockReservationId");

                            b1.ToTable("stock_reservations", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockReservationId");
                        });

                    b.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Quantity", b1 =>
                        {
                            b1.Property<Guid>("StockReservationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("qty_amount");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("qty_unit");

                            b1.HasKey("StockReservationId");

                            b1.ToTable("stock_reservations", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("StockReservationId");
                        });

                    b.Navigation("Allocated")
                        .IsRequired();

                    b.Navigation("Quantity")
                        .IsRequired();
                });

            modelBuilder.Entity("Warehouse.Warehousing.Inventory.Domain.Stocktake", b =>
                {
                    b.OwnsMany("Warehouse.Warehousing.Inventory.Domain.CountLine", "Lines", b1 =>
                        {
                            b1.Property<Guid>("stocktake_id")
                                .HasColumnType("uuid");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Batch")
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("batch");

                            b1.Property<string>("CountedBy")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("counted_by");

                            b1.Property<string>("Location")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("location");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("sku");

                            b1.HasKey("stocktake_id", "Id");

                            b1.ToTable("stocktake_count_lines", "inventory");

                            b1.WithOwner()
                                .HasForeignKey("stocktake_id");

                            b1.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Counted", b2 =>
                                {
                                    b2.Property<Guid>("CountLinestocktake_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("CountLineId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("numeric(18,3)")
                                        .HasColumnName("counted_amount");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("counted_unit");

                                    b2.HasKey("CountLinestocktake_id", "CountLineId");

                                    b2.ToTable("stocktake_count_lines", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("CountLinestocktake_id", "CountLineId");
                                });

                            b1.OwnsOne("Warehouse.SharedKernel.ValueObjects.Quantity", "Expected", b2 =>
                                {
                                    b2.Property<Guid>("CountLinestocktake_id")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("CountLineId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("Amount")
                                        .HasPrecision(18, 3)
                                        .HasColumnType("numeric(18,3)")
                                        .HasColumnName("expected_amount");

                                    b2.Property<string>("Unit")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("expected_unit");

                                    b2.HasKey("CountLinestocktake_id", "CountLineId");

                                    b2.ToTable("stocktake_count_lines", "inventory");

                                    b2.WithOwner()
                                        .HasForeignKey("CountLinestocktake_id", "CountLineId");
                                });

                            b1.Navigation("Counted")
                                .IsRequired();

                            b1.Navigation("Expected")
                                .IsRequired();
                        });

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
