// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.Warehousing.Topology.Infrastructure.Persistence;

#nullable disable

namespace Warehouse.Warehousing.Topology.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TopologyDbContext))]
    partial class TopologyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("topology")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.Warehousing.Topology.Domain.WarehouseSite", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("warehouses", "topology");
                });

            modelBuilder.Entity("Warehouse.Warehousing.Topology.Domain.WarehouseSite", b =>
                {
                    b.OwnsOne("Warehouse.SharedKernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<string>("WarehouseSiteId")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)")
                                .HasColumnName("city");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("country_code");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street");

                            b1.HasKey("WarehouseSiteId");

                            b1.ToTable("warehouses", "topology");

                            b1.WithOwner()
                                .HasForeignKey("WarehouseSiteId");
                        });

                    b.OwnsMany("Warehouse.Warehousing.Topology.Domain.Dock", "Docks", b1 =>
                        {
                            b1.Property<string>("warehouse_code")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Id")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("code");

                            b1.Property<string>("Direction")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("direction");

                            b1.HasKey("warehouse_code", "Id");

                            b1.ToTable("docks", "topology");

                            b1.WithOwner()
                                .HasForeignKey("warehouse_code");
                        });

                    b.OwnsMany("Warehouse.Warehousing.Topology.Domain.Room", "Rooms", b1 =>
                        {
                            b1.Property<string>("warehouse_code")
                                .HasColumnType("character varying(10)");

                            b1.Property<string>("Id")
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("code");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("type");

                            b1.HasKey("warehouse_code", "Id");

                            b1.ToTable("rooms", "topology");

                            b1.WithOwner()
                                .HasForeignKey("warehouse_code");

                            b1.OwnsOne("Warehouse.Warehousing.Topology.Domain.RoomEnvironment", "Environment", b2 =>
                                {
                                    b2.Property<string>("Roomwarehouse_code")
                                        .HasColumnType("character varying(10)");

                                    b2.Property<string>("RoomId")
                                        .HasColumnType("character varying(10)");

                                    b2.Property<bool>("HumidityControlled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("humidity_controlled");

                                    b2.HasKey("Roomwarehouse_code", "RoomId");

                                    b2.ToTable("rooms", "topology");

                                    b2.WithOwner()
                                        .HasForeignKey("Roomwarehouse_code", "RoomId");

                                    b2.OwnsOne("Warehouse.SharedKernel.ValueObjects.TemperatureRange", "MaintainedTemperature", b3 =>
                                        {
                                            b3.Property<string>("RoomEnvironmentRoomwarehouse_code")
                                                .HasColumnType("character varying(10)");

                                            b3.Property<string>("RoomEnvironmentRoomId")
                                                .HasColumnType("character varying(10)");

                                            b3.Property<decimal>("MaxCelsius")
                                                .HasPrecision(6, 2)
                                                .HasColumnType("numeric(6,2)")
                                                .HasColumnName("temp_max_c");

                                            b3.Property<decimal>("MinCelsius")
                                                .HasPrecision(6, 2)
                                                .HasColumnType("numeric(6,2)")
                                                .HasColumnName("temp_min_c");

                                            b3.HasKey("RoomEnvironmentRoomwarehouse_code", "RoomEnvironmentRoomId");

                                            b3.ToTable("rooms", "topology");

                                            b3.WithOwner()
                                                .HasForeignKey("RoomEnvironmentRoomwarehouse_code", "RoomEnvironmentRoomId");
                                        });

                                    b2.Navigation("MaintainedTemperature")
                                        .IsRequired();
                                });

                            b1.OwnsMany("Warehouse.Warehousing.Topology.Domain.Location", "Locations", b2 =>
                                {
                                    b2.Property<string>("warehouse_code")
                                        .HasColumnType("character varying(10)");

                                    b2.Property<string>("room_code")
                                        .HasColumnType("character varying(10)");

                                    b2.Property<string>("Id")
                                        .HasMaxLength(60)
                                        .HasColumnType("character varying(60)")
                                        .HasColumnName("code");

                                    b2.Property<decimal>("Capacity")
                                        .HasPrecision(12, 4)
                                        .HasColumnType("numeric(12,4)")
                                        .HasColumnName("capacity_m3");

                                    b2.Property<string>("Kind")
                                        .IsRequired()
                                        .HasMaxLength(16)
                                        .HasColumnType("character varying(16)")
                                        .HasColumnName("kind");

                                    b2.Property<decimal>("MaxLoad")
                                        .HasPrecision(12, 3)
                                        .HasColumnType("numeric(12,3)")
                                        .HasColumnName("max_load_kg");

                                    b2.HasKey("warehouse_code", "room_code", "Id");

                                    b2.ToTable("locations", "topology");

                                    b2.WithOwner()
                                        .HasForeignKey("warehouse_code", "room_code");
                                });

                            b1.Navigation("Environment")
                                .IsRequired();

                            b1.Navigation("Locations");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Docks");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
