// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Warehouse.MasterData.Catalog.Infrastructure.Persistence;

#nullable disable

namespace Warehouse.MasterData.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Warehouse.MasterData.Catalog.Domain.ProductType", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("sku");

                    b.Property<string>("BaseUnit")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("base_unit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("category");

                    b.Property<string>("Ean")
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)")
                        .HasColumnName("ean");

                    b.Property<bool>("HasExpiryDate")
                        .HasColumnType("boolean")
                        .HasColumnName("has_expiry_date");

                    b.Property<bool>("IsBatchTracked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_batch_tracked");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("UnitWeight")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("unit_weight_kg");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("Ean")
                        .IsUnique();

                    b.ToTable("product_types", "catalog");
                });

            modelBuilder.Entity("Warehouse.MasterData.Catalog.Domain.ProductType", b =>
                {
                    b.OwnsOne("Warehouse.MasterData.Catalog.Domain.Dimensions", "Dimensions", b1 =>
                        {
                            b1.Property<string>("ProductTypeId")
                                .HasColumnType("character varying(32)");

                            b1.Property<decimal>("HeightCm")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("height_cm");

                            b1.Property<decimal>("LengthCm")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("length_cm");

                            b1.Property<decimal>("WidthCm")
                                .HasPrecision(10, 2)
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("width_cm");

                            b1.HasKey("ProductTypeId");

                            b1.ToTable("product_types", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductTypeId");
                        });

                    b.OwnsOne("Warehouse.MasterData.Catalog.Domain.StorageRequirement", "Storage", b1 =>
                        {
                            b1.Property<string>("ProductTypeId")
                                .HasColumnType("character varying(32)");

                            b1.Property<bool>("IsHazardous")
                                .HasColumnType("boolean")
                                .HasColumnName("is_hazardous");

                            b1.Property<bool>("RequiresColdChain")
                                .HasColumnType("boolean")
                                .HasColumnName("requires_cold_chain");

                            b1.HasKey("ProductTypeId");

                            b1.ToTable("product_types", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductTypeId");

                            b1.OwnsOne("Warehouse.SharedKernel.ValueObjects.TemperatureRange", "Temperature", b2 =>
                                {
                                    b2.Property<string>("StorageRequirementProductTypeId")
                                        .HasColumnType("character varying(32)");

                                    b2.Property<decimal>("MaxCelsius")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("temp_max_c");

                                    b2.Property<decimal>("MinCelsius")
                                        .HasPrecision(6, 2)
                                        .HasColumnType("numeric(6,2)")
                                        .HasColumnName("temp_min_c");

                                    b2.HasKey("StorageRequirementProductTypeId");

                                    b2.ToTable("product_types", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("StorageRequirementProductTypeId");
                                });

                            b1.Navigation("Temperature");
                        });

                    b.OwnsMany("Warehouse.MasterData.Catalog.Domain.UnitConversion", "UnitConversions", b1 =>
                        {
                            b1.Property<string>("ProductTypeId")
                                .HasColumnType("character varying(32)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("FactorToBase")
                                .HasPrecision(18, 6)
                                .HasColumnType("numeric(18,6)")
                                .HasColumnName("factor_to_base");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("unit");

                            b1.HasKey("ProductTypeId", "Id");

                            b1.ToTable("product_unit_conversions", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductTypeId");
                        });

                    b.Navigation("Dimensions")
                        .IsRequired();

                    b.Navigation("Storage")
                        .IsRequired();

                    b.Navigation("UnitConversions");
                });
#pragma warning restore 612, 618
        }
    }
}
